// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rikka.proto

package rikka

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QueryRequest struct {
	Passage              string   `protobuf:"bytes,1,opt,name=passage,proto3" json:"passage,omitempty"`
	Question             string   `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e37513e3e56fce4, []int{0}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetPassage() string {
	if m != nil {
		return m.Passage
	}
	return ""
}

func (m *QueryRequest) GetQuestion() string {
	if m != nil {
		return m.Question
	}
	return ""
}

type AnswerReply struct {
	Answer               string   `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	Score                string   `protobuf:"bytes,2,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnswerReply) Reset()         { *m = AnswerReply{} }
func (m *AnswerReply) String() string { return proto.CompactTextString(m) }
func (*AnswerReply) ProtoMessage()    {}
func (*AnswerReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e37513e3e56fce4, []int{1}
}

func (m *AnswerReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnswerReply.Unmarshal(m, b)
}
func (m *AnswerReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnswerReply.Marshal(b, m, deterministic)
}
func (m *AnswerReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnswerReply.Merge(m, src)
}
func (m *AnswerReply) XXX_Size() int {
	return xxx_messageInfo_AnswerReply.Size(m)
}
func (m *AnswerReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AnswerReply.DiscardUnknown(m)
}

var xxx_messageInfo_AnswerReply proto.InternalMessageInfo

func (m *AnswerReply) GetAnswer() string {
	if m != nil {
		return m.Answer
	}
	return ""
}

func (m *AnswerReply) GetScore() string {
	if m != nil {
		return m.Score
	}
	return ""
}

type SumRequest struct {
	Passage              string   `protobuf:"bytes,1,opt,name=passage,proto3" json:"passage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumRequest) Reset()         { *m = SumRequest{} }
func (m *SumRequest) String() string { return proto.CompactTextString(m) }
func (*SumRequest) ProtoMessage()    {}
func (*SumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e37513e3e56fce4, []int{2}
}

func (m *SumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumRequest.Unmarshal(m, b)
}
func (m *SumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumRequest.Marshal(b, m, deterministic)
}
func (m *SumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumRequest.Merge(m, src)
}
func (m *SumRequest) XXX_Size() int {
	return xxx_messageInfo_SumRequest.Size(m)
}
func (m *SumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SumRequest proto.InternalMessageInfo

func (m *SumRequest) GetPassage() string {
	if m != nil {
		return m.Passage
	}
	return ""
}

type SumReply struct {
	Summary              string   `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumReply) Reset()         { *m = SumReply{} }
func (m *SumReply) String() string { return proto.CompactTextString(m) }
func (*SumReply) ProtoMessage()    {}
func (*SumReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e37513e3e56fce4, []int{3}
}

func (m *SumReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumReply.Unmarshal(m, b)
}
func (m *SumReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumReply.Marshal(b, m, deterministic)
}
func (m *SumReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumReply.Merge(m, src)
}
func (m *SumReply) XXX_Size() int {
	return xxx_messageInfo_SumReply.Size(m)
}
func (m *SumReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SumReply.DiscardUnknown(m)
}

var xxx_messageInfo_SumReply proto.InternalMessageInfo

func (m *SumReply) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

type QuestionRequest struct {
	Passage              string   `protobuf:"bytes,1,opt,name=passage,proto3" json:"passage,omitempty"`
	Term                 string   `protobuf:"bytes,2,opt,name=term,proto3" json:"term,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuestionRequest) Reset()         { *m = QuestionRequest{} }
func (m *QuestionRequest) String() string { return proto.CompactTextString(m) }
func (*QuestionRequest) ProtoMessage()    {}
func (*QuestionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e37513e3e56fce4, []int{4}
}

func (m *QuestionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuestionRequest.Unmarshal(m, b)
}
func (m *QuestionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuestionRequest.Marshal(b, m, deterministic)
}
func (m *QuestionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuestionRequest.Merge(m, src)
}
func (m *QuestionRequest) XXX_Size() int {
	return xxx_messageInfo_QuestionRequest.Size(m)
}
func (m *QuestionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuestionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuestionRequest proto.InternalMessageInfo

func (m *QuestionRequest) GetPassage() string {
	if m != nil {
		return m.Passage
	}
	return ""
}

func (m *QuestionRequest) GetTerm() string {
	if m != nil {
		return m.Term
	}
	return ""
}

type QuestionReply struct {
	Question             string   `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuestionReply) Reset()         { *m = QuestionReply{} }
func (m *QuestionReply) String() string { return proto.CompactTextString(m) }
func (*QuestionReply) ProtoMessage()    {}
func (*QuestionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e37513e3e56fce4, []int{5}
}

func (m *QuestionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuestionReply.Unmarshal(m, b)
}
func (m *QuestionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuestionReply.Marshal(b, m, deterministic)
}
func (m *QuestionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuestionReply.Merge(m, src)
}
func (m *QuestionReply) XXX_Size() int {
	return xxx_messageInfo_QuestionReply.Size(m)
}
func (m *QuestionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_QuestionReply.DiscardUnknown(m)
}

var xxx_messageInfo_QuestionReply proto.InternalMessageInfo

func (m *QuestionReply) GetQuestion() string {
	if m != nil {
		return m.Question
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryRequest)(nil), "QueryRequest")
	proto.RegisterType((*AnswerReply)(nil), "AnswerReply")
	proto.RegisterType((*SumRequest)(nil), "SumRequest")
	proto.RegisterType((*SumReply)(nil), "SumReply")
	proto.RegisterType((*QuestionRequest)(nil), "QuestionRequest")
	proto.RegisterType((*QuestionReply)(nil), "QuestionReply")
}

func init() { proto.RegisterFile("rikka.proto", fileDescriptor_7e37513e3e56fce4) }

var fileDescriptor_7e37513e3e56fce4 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0x5b, 0xab, 0xfb, 0xe7, 0x75, 0x57, 0x21, 0x88, 0x94, 0x5e, 0x94, 0x61, 0x29, 0xc2,
	0x62, 0x0e, 0xf5, 0xe8, 0x41, 0x04, 0xaf, 0x1e, 0xb6, 0xfb, 0x09, 0xa2, 0x04, 0x29, 0x6b, 0xb6,
	0x35, 0x69, 0x90, 0x7e, 0x7b, 0xd9, 0x34, 0x75, 0xbb, 0x5e, 0x7a, 0x9a, 0xfc, 0xc8, 0xe4, 0xcd,
	0x7b, 0x13, 0xc4, 0xba, 0xdc, 0xed, 0x04, 0xaf, 0x75, 0xd5, 0x54, 0xf4, 0x8a, 0xc5, 0xc6, 0x4a,
	0xdd, 0x16, 0xf2, 0xdb, 0x4a, 0xd3, 0xb0, 0x04, 0xd3, 0x5a, 0x18, 0x23, 0x3e, 0x65, 0x12, 0xde,
	0x85, 0xf7, 0xf3, 0xa2, 0x47, 0x96, 0x62, 0xe6, 0x5a, 0xca, 0x6a, 0x9f, 0x9c, 0xb9, 0xab, 0x3f,
	0xa6, 0x27, 0xc4, 0x2f, 0x7b, 0xf3, 0x23, 0x75, 0x21, 0xeb, 0xaf, 0x96, 0xdd, 0x60, 0x22, 0x1c,
	0x7a, 0x0d, 0x4f, 0xec, 0x1a, 0x17, 0xe6, 0xa3, 0xd2, 0xd2, 0xbf, 0xef, 0x80, 0x32, 0x60, 0x6b,
	0xd5, 0xa8, 0x01, 0x5a, 0x61, 0xe6, 0xfa, 0x0e, 0x13, 0x12, 0x4c, 0x8d, 0x55, 0x4a, 0xe8, 0xb6,
	0xef, 0xf2, 0x48, 0xcf, 0xb8, 0xda, 0x78, 0x5b, 0xe3, 0x99, 0x18, 0xce, 0x1b, 0xa9, 0x95, 0xf7,
	0xe3, 0xce, 0xb4, 0xc6, 0xf2, 0x28, 0x70, 0x98, 0x35, 0x0c, 0x1e, 0x9e, 0x06, 0xcf, 0xd7, 0x88,
	0xde, 0x44, 0xc9, 0x56, 0x5d, 0x59, 0xf2, 0xe1, 0x2e, 0xd3, 0x05, 0x1f, 0x2c, 0x85, 0x82, 0x3c,
	0x43, 0xb4, 0xb5, 0x8a, 0xdd, 0x76, 0x25, 0xe6, 0xc7, 0xd4, 0xe9, 0x9c, 0xf7, 0xd1, 0x28, 0xc8,
	0x1f, 0x10, 0x15, 0xb6, 0x64, 0x59, 0x57, 0xfe, 0x89, 0x5e, 0xf2, 0x13, 0x77, 0x14, 0xbc, 0x4f,
	0xdc, 0x4f, 0x3e, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0xc5, 0xeb, 0x14, 0x4d, 0xd8, 0x01, 0x00,
	0x00,
}
